# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image: python:latest

run:
  script:
    - python -m pip install wemake-python-styleguide
    - flake8 .
