name: Check_Playlist
on:
  workflow_run:
    workflows: ["Build"]
    types: [requested]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install wemake-python-styleguide
    - name: wemake-python-styleguide            
      uses: wemake-services/wemake-python-styleguide@0.18.0
